project:
  type: website
  output-dir: docs

website:
  title: "Chris's 2023 DSPG Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cjseeger/chris_dspg_blog
      - icon: twitter
        href: https://twitter.com/profseeger
      - icon: linkedin
        href: https://www.linkedin.com/in/christopher-j-seeger/

format:
  html:
    theme: lumon
    css: styles.css

editor: visual

