---
title: "Week 2"
author: "Chris Seeger"
date: "2023-05-25"
categories: "Week Two"
---

# Chris's DSPG Blog Week 2

```{r warning=FALSE, message=FALSE, eval=FALSE}
install.packages(c("tidycensus", "tidyverse"))
library(tidycensus)
library(tidyverse)

vars <- load_variables(2021, "acs5")
View(vars)
```

### Example of an embeded Tableau Dashboard

```{r include=FALSE}
x = 2
```

```{=html}
<script type="module" src="https://public.tableau.com/javascripts/api/tableau.embedding.3.latest.js"></script>

  <div style="width:800px; height:700px;">
<tableau-viz id="tableauViz" src="  https://public.tableau.com/app/profile/christopher.seeger/viz/IowaLanguagesSpoken/Dashboard1" toolbar="bottom" hide-tabs>
</tableau-viz>
    </div>
```
```{=html}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Chris Practice</title>
  
     <!-- Tableau JS API-->
    <script type="text/javascript" src="https://tableau.vdl.iastate.edu/javascripts/api/tableau-2.min.js"></script>
  
  

  
  
</head>
<body>
Trying to display a Tableau page.
  <script>
  var containerDiv = document.getElementById("vizContainer"),

          url = "https://tableau.vdl.iastate.edu/t/COMXT/views/CountyEnglishLanguageK-12/CountyK-12EL",

          options = {
            hideTabs: true,
            hideToolbar: true,
            onFirstInteractive: function() {
              console.log("Run this code when the viz has finished loading.");
            }
          };

        viz = new tableau.Viz(containerDiv, url, options);
        // Create a viz object and embed it in the container div.
  </script>
  
</body>
</html>
```
